%YAML:1.0
image_width: 640
image_height: 480
camera_name: narrow_stereo
camera_matrix: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [724.802854, 0, 301.024339, 0, 726.958453, 225.429107, 0, 0, 1]
distortion_model: plumb_bob
open: !!opencv-matrix
   rows: 1
   cols: 5
   dt: d
   data: [0.263029, -0.857592, 0.0014, -0.001215, 0]
rectification_matrix: !!opencv-matrix
   rows: 3
   cols: 3
   dt: u
   data: [1, 0, 0, 0, 1, 0, 0, 0, 1]
projection_matrix: !!opencv-matrix
   rows: 3
   cols: 4
   dt: d
   data: [736.966858, 0, 299.612002, 0, 0, 740.353638, 225.373243, 0, 0, 0, 1, 0]