%YAML:1.0
image_width: 1280
image_height: 720
camera_name: narrow_stereo
camera_matrix: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [1118.270139, 0, 662.010610, 0, 1115.511059, 325.969067, 0, 0, 1]
distortion_model: plumb_bob
open: !!opencv-matrix
   rows: 1
   cols: 5
   dt: d
   data: [0.004304, -0.094863, -0.002516, 0.007461, 0.0]
rectification_matrix: !!opencv-matrix
   rows: 3
   cols: 3
   dt: u
   data: [1, 0, 0, 0, 1, 0, 0, 0, 1]
projection_matrix: !!opencv-matrix
   rows: 3
   cols: 4
   dt: d
   data: [736.966858, 0, 299.612002, 0, 0, 740.353638, 225.373243, 0, 0, 0, 1, 0]